/*
 * Copyright (C) 2026 University of Freiburg
 * Copyright (C) 2026 LMU Munich
 *
 * This file is part of the ULTIMATE TraceAbstraction plug-in.
 *
 * Generated by AI
 */
package multiprocessed;

import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.Map;

import de.uni_freiburg.informatik.ultimate.automata.nestedword.NestedRun;

/** Coordinator-owned view of dispatched multiprocessing jobs. */
interface IActiveJobRegistry<L> {
	enum State {
		DISPATCHED, RUNNING, CANCELLED, COMPLETED
	}

	final class Job<L> {
		private final String mJobId;
		private final NestedRun<L, ?> mCounterexample;
		private final int mAbstractionGeneration;
		private final String mPathProgramHash;
		private State mState = State.DISPATCHED;
		private String mWorkerId;
		private Long mWorkerPid;

		Job(final String jobId, final NestedRun<L, ?> counterexample, final int abstractionGeneration,
				final String pathProgramHash) {
			mJobId = jobId;
			mCounterexample = counterexample;
			mAbstractionGeneration = abstractionGeneration;
			mPathProgramHash = pathProgramHash;
		}

		String jobId() {
			return mJobId;
		}

		NestedRun<L, ?> counterexample() {
			return mCounterexample;
		}

		int abstractionGeneration() {
			return mAbstractionGeneration;
		}

		String pathProgramHash() {
			return mPathProgramHash;
		}

		State state() {
			return mState;
		}

		String workerId() {
			return mWorkerId;
		}

		Long workerPid() {
			return mWorkerPid;
		}
	}

	void register(String jobId, NestedRun<L, ?> counterexample, int abstractionGeneration, String pathProgramHash);

	Collection<Job<L>> activeJobs();

	void assign(String jobId, String workerId, long workerPid);

	void cancel(String jobId);

	void complete(String jobId);

	final class InMemory<L> implements IActiveJobRegistry<L> {
		private final Map<String, Job<L>> mJobs = new LinkedHashMap<>();

		@Override
		public void register(final String jobId, final NestedRun<L, ?> counterexample, final int abstractionGeneration,
				final String pathProgramHash) {
			if (mJobs.putIfAbsent(jobId,
					new Job<>(jobId, counterexample, abstractionGeneration, pathProgramHash)) != null) {
				throw new IllegalArgumentException("Duplicate multiprocessing job " + jobId);
			}
		}

		@Override
		public Collection<Job<L>> activeJobs() {
			return mJobs.values().stream().filter(x -> x.mState == State.DISPATCHED || x.mState == State.RUNNING)
					.toList();
		}

		@Override
		public void assign(final String jobId, final String workerId, final long workerPid) {
			final Job<L> job = mJobs.get(jobId);
			if (job != null && job.mState == State.DISPATCHED) {
				job.mWorkerId = workerId;
				job.mWorkerPid = workerPid;
				job.mState = State.RUNNING;
			}
		}

		@Override
		public void cancel(final String jobId) {
			setTerminalState(jobId, State.CANCELLED);
		}

		@Override
		public void complete(final String jobId) {
			setTerminalState(jobId, State.COMPLETED);
		}

		private void setTerminalState(final String jobId, final State state) {
			final Job<L> job = mJobs.get(jobId);
			if (job != null && job.mState != State.CANCELLED && job.mState != State.COMPLETED) {
				job.mState = state;
			}
		}
	}
}
